=== TusharTalekar/TE-Lab/WTL/Assignment4/employees.dtd
<!ELEMENT employees (employee+)>

<!ELEMENT employee (name, department, designation, salary, email)>
<!ATTLIST employee id CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== TusharTalekar/TE-Lab/WTL/Assignment4/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<?xml-stylesheet type="text/xsl" href="employees.xsl"?>
<employees>
    <employee id="E101">
        <name>Manoj Kumar</name>
        <department>IT</department>
        <designation>Software Engineer</designation>
        <salary>60000</salary>
        <email>Manoj@company.com</email>
    </employee>

    <employee id="E102">
        <name>Anita Sharma</name>
        <department>HR</department>
        <designation>HR Manager</designation>
        <salary>55000</salary>
        <email>anita@company.com</email>
    </employee>
</employees>
